# Generated by Django 4.1.3 on 2022-12-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام')),
                ('serial_number', models.IntegerField(max_length=11, verbose_name='سریال')),
                ('is_active', models.BooleanField(verbose_name='در سایت وجود داشته باشد؟؟')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
            ],
        ),
    ]
