# Generated by Django 4.1.3 on 2022-12-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.categories', verbose_name='دسته بندی ارشد')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام آموزشگاه'),
        ),
        migrations.AlterField(
            model_name='company',
            name='serial_number',
            field=models.IntegerField(max_length=11, verbose_name='سریال آموزشگاه'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='اسلاگ'),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام دوره')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('desc', models.TextField(verbose_name='توضیحات')),
                ('img', models.ImageField(default='class_pic/default_class.png', upload_to='class_pic/', verbose_name='عکس')),
                ('price', models.IntegerField(max_length=10, verbose_name='قیمت دوره')),
                ('is_active', models.BooleanField(verbose_name='در سایت وجود داشته باشد؟؟')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.categories', verbose_name='دسته بندی')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.company', verbose_name='آموزشگاه')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.categories', verbose_name='دسته بندی'),
        ),
    ]
