# Generated by Django 4.1.3 on 2022-12-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_categories_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاس ها'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'آموزشگاه', 'verbose_name_plural': 'آموشگاه ها'},
        ),
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.ImageField(default='company_pic/default_class.png', upload_to='company_pic/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='company',
            name='serial_number',
            field=models.IntegerField(max_length=11, unique=True, verbose_name='سریال آموزشگاه'),
        ),
    ]
