# Generated by Django 4.1.3 on 2022-12-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_categories_options_alter_classes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.categories', verbose_name='دسته بندی ارشد'),
        ),
    ]
