# Generated by Django 4.1.3 on 2022-12-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_categories_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='desc',
            field=models.TextField(default='توضیحات', verbose_name='توضیحات'),
        ),
    ]
