# Generated by Django 4.1.2 on 2022-12-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_company_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='classes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classes.categories', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classes.company', verbose_name='آموزشگاه'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='price',
            field=models.IntegerField(verbose_name='قیمت دوره'),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='classes.categories', verbose_name='دسته بندی'),
        ),
    ]
