# Generated by Django 4.1.7 on 2023-02-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_city_company_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس ای پی')),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['position'], 'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.AlterField(
            model_name='city',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='منطقه قرارگیری'),
        ),
        migrations.AddField(
            model_name='classes',
            name='views',
            field=models.ManyToManyField(blank=True, to='classes.ipaddress', verbose_name='بازدید'),
        ),
    ]
