# Generated by Django 4.1.2 on 2022-11-30 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('img', models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pic/', verbose_name='عکس')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
            ],
        ),
    ]
