# Generated by Django 4.1.7 on 2023-02-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_company_serial_number_alter_classes_category_and_more'),
        ('accounts', '0004_alter_user_options_remove_user_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, to='classes.classes', verbose_name='دوره ها'),
        ),
    ]
