# Generated by Django 4.1.7 on 2023-02-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_ipaddress_alter_city_options_alter_city_position_and_more'),
        ('accounts', '0005_alter_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.company', verbose_name='موسسه'),
        ),
    ]
